# encoding=utf-8
# Generated by cpy
#!/usr/bin/python env

import md5
import hashlib
from SSDB import SSDB

def getMD5(strMessage):
    strMD5 = ''
    md5c   = hashlib.md5()
    md5c.update(strMessage)
    strMD5 = md5c.hexdigest()[8:24]
    return strMD5

class MySSDB():
	_ssdb = None

	def __init__(self, host='127.0.0.1', port = 8888):
		self._ssdb = SSDB(host, port)

	def isHItemInDB(self, dbname, item):
		req = self._ssdb.request('hget', [dbname, item])
		return req.code == 'ok'

	def getHItem(self, dbname, item):
		req = self._ssdb.request('hget', [dbname, item] )
		if req.code == 'ok':
			return req.data
		else:
			return ''

	def getHValueByItem(self, dbname, item):
		req = self._ssdb.request('hget', [dbname, item] )
		if req.code == 'ok':
			return req.data
		else:
			return ''

	def getHSize(self, dbname):
		req = self._ssdb.request('hsize',[dbname])
		if req.code == 'ok':
			return req.data
		else:
			return 0

	def setHItem(self, dbname, item, value):
		try:
			req = self._ssdb.request('hset',[dbname, item, value])
		except Exception, e:
			print e

	def isDomainInDB(self, dbname, domain):
		return self.isHItemInDB(dbname, getMD5(domain))
