# encoding=utf-8
# Generated by cpy
#!/usr/bin/python env

import md5
import hashlib
from SSDB import SSDB

ssdb = SSDB('127.0.0.1', 8888)


def getMD5(strMessage):
    strMD5 = ''
    md5c   = hashlib.md5()
    md5c.update(strMessage)
    strMD5 = md5c.hexdigest()[8:24]
    return strMD5

class MySSDB():

	@staticmethod
	def isHItemInDB(dbname, item):
		req = ssdb.request('hget', [dbname, item])
		return req.code == 'ok'

	@staticmethod
	def getHItem(dbname, item):
		req = ssdb.request('hget', [dbname, item] )
		if req.code == 'ok':
			return req.data
		else:
			return ''

	@staticmethod
	def getHValueByItem(dbname, item):
		req = ssdb.request('hget', [dbname, item] )
		if req.code == 'ok':
			return req.data
		else:
			return ''

	@staticmethod
	def getHSize(dbname):
		req = ssdb.request('hsize',[dbname])
		if req.code == 'ok':
			return req.data
		else:
			return 0

	@staticmethod
	def setHItem(dbname, item, value):
		try:
			req = ssdb.request('hset',[dbname, item, value])
		except Exception, e:
			print e

	@staticmethod
	def isDomainInDB(dbname, domain):
		return MySSDB.isHItemInDB(dbname, getMD5(domain))
